seed: 0 
fully_overwrite: False

# Datasets
download: True
websites: 
  biqmac: "https://biqmac.aau.at/biqmaclib.html"
  yyye: "https://web.stanford.edu/~yyye/yyye/Gset/"

# Stable set
stable_set:
  max_vertices: 200
  max_matrix: 7000
  c_projection:
    - 0.1
    - 0.2
  projector: 
    - "sparse"
    - "sparser"
    - "0.1_density"
    - "0.2_density"
petersen_n_k:
  - n: 20
    k: 2
  - n: 30
    k: 2
  - n: 40
    k: 2
  - n: 50
    k: 2
cordones:
  - n: 20
  - n: 30
  - n: 40


# Maxcut
maxcut:
  max_vertices: 7000
  min_vertices: 7000
  weighted: False
  projector: 
    # - "sparser"
    # - "sparse"
    # - "0.1_density"
    # - "0.2_density"
    # - "0.02_density"
    # - "0.03_density"
    # - "0.05_density"
    - "0.04_density"
    # - "0.01_density"
  projection:
    - 0.1
    # - 0.2
    # - 0.5
  results:
    min_vertices: 5000
    max_vertices: 5000
  name: "mcp"
    # - "G"
    # - "mcp"


# Maxsat
maxsat:
  variables:
    # - 1000
    # - 1500
    # - 2000
    # - 3000
    - 5000
    - 7000
  C:
    - 0.5
    - 1
    - 5
    - 10
    # - 10
    # - 20
  projection:
    - 0.1
    - 0.2
    # - 0.5

densities:
  - 800: "sparse"
  - 1000: "sparse"
  - 2000: "0.2_density"
  - 3000: "0.2_density"
  - 4000: "0.1_density"
  - 5000: "0.05_density"
  - 6000: "0.05_density"
  - 7000: "0.04_density"
