seed: 0 
fully_overwrite: False

# Datasets
download: True
websites: 
  biqmac: "https://biqmac.aau.at/biqmaclib.html"
  yyye: "https://web.stanford.edu/~yyye/yyye/Gset/"

# Stable set
stable_set:
  max_vertices: 200
  max_matrix: 7000
  c_projection:
    - 0.1
    - 0.2
  projector: 
    - "sparse"
    - "sparser"
    - "0.1_density"
    - "0.2_density"
petersen_n_k:
  - n: 10
    k: 2
#   - n: 30
#     k: 2
#   - n: 40
#     k: 2
#   - n: 50
#     k: 2
cordones:
  - n: 5
#   - n: 30
#   - n: 40


# Maxcut
maxcut:
  max_vertices: 7000
  min_vertices: 7000
  weighted: False
  projector: 
    # - "sparser"
    # - "sparse"
    # - "0.1_density"
    # - "0.2_density"
    # - "0.02_density"
    # - "0.03_density"
    # - "0.05_density"
    - "0.04_density"
    # - "0.01_density"
  projection:
    - 0.1
    # - 0.2
    # - 0.5
  results:
    min_vertices: 7000
    max_vertices: 7000
  name: "mcp"
    # - "G"
    # - "mcp"


# Maxsat
maxsat:
  variables:
    - 1000
    - 1500
    - 2000
    # - 3000
    # - 5000
  C:
    - 0.1
    # - 0.5
    # - 1
    # - 2
    # - 10
    # - 20
  projector:
    - "sparse"
    # - "sparser"
    - "0.1_density"
    - "0.2_density"
    # - "0.05_density"
  projection:
    - 0.1
    - 0.2
    # - 0.5
