seed: 0 
fully_overwrite: False

# Datasets
download: True
websites: 
  biqmac: "https://biqmac.aau.at/biqmaclib.html"
  yyye: "https://web.stanford.edu/~yyye/yyye/Gset/"

# Stable set
stable_set:
  max_vertices: 200
  max_matrix: 7000
  projection:
    - 0.5 
    - 0.6
  c_projection:
    - 0.1
    - 0.2
  projector: 
    - "sparse"
    - "sparser"
    - "0.1_density"
    - "0.2_density"
petersen_n_k:
  # - n: 5
  #   k: 2
  - n: 20
    k: 2
  - n: 30
    k: 2
  - n: 40
    k: 2
cordones:
  # - n: 5
  - n: 20
  - n: 30
  # - n: 40
helm:
  # - n: 5
  - n: 21
  - n: 31
  # - n: 41
jahangir:
  - n: 17
    k: 2
  - n: 19
    k: 3
  - n: 41
    k: 2



# Maxcut
maxcut:
  max_vertices: 10000
  min_vertices: 10000
  weighted: False
  projection:
    - 0.05
    - 0.1
    # - 0.2
    # - 0.5
  results:
    min_vertices: 7000
    max_vertices: 7000
  name: "mcp"
    # - "G"
    # - "mcp"


# Maxsat
maxsat:
  random: False
  min_variables: 5000
  max_variables: 5000
  variables:
    # - 1000
    # - 1500
    # - 2000
    # - 3000
    - 5000
    - 7000
  C:
    # - 0.5
    # - 1
    # - 3
    # - 5
  projection:
    - 0.1
    # - 0.2
    # - 0.5

  # SAT
sat:
  random: True
  min_variables: 5000
  max_variables: 5000
  variables:
    # - 500
    # - 1000
    - 2000
  C:
    # - 0.5
    # - 1
    - 2
  projection:
    - 0.2
    - 0.5
  repetitions: 200

# QCQPs
qcqp:
  variables: 
    - 500
    - 1000
    - 2000
    # - 5000
    # - 7000
  q:
    - 0.1
    - 0.5
    - 1
  projection:
    - 0.5
    - 0.7

#Unit sphere
unit_sphere:
  variables:
    - 20
    # - 15
    # - 20

  degree: 
    - 4
    # - 6

  projection:
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    # - 0.7
    # - 0.75
    # - 0.8
    # - 0.85
    # - 0.9
    # - 0.95

  seed:
    # - 0
    - 1
    # - 3



densities:
  0, 400:
    # - "sparse"
    - "0.1_density"
  401, 1200:
    # - "0.2_density"
    - "0.05_density"
  1201, 4000:
    - "0.1_density"
  4001, 5000:
    - "0.06_density"
  5001, 6000:
    - "0.05_density"
  6001, 7000:
    - "0.04_density"
  7001, 8000:
    - "0.03_density"
  8001, 9000:
    - "0.02_density"
  9001, 10000:
    - "0.01_density"
  10001, 15000:
    - "0.005_density"

