seed: 0 
fully_overwrite: False

# Datasets
download: True
websites: 
  biqmac: "https://biqmac.aau.at/biqmaclib.html"
  yyye: "https://web.stanford.edu/~yyye/yyye/Gset/"

# Stable set
stable_set:
  max_vertices: 25
  projection:
    - 0.5
    - 0.6
    - 0.7
    - 0.8
  c_projection:
    - 0.05
    - 0.1
    - 0.2
  projector: 
    - "sparse"
    - "sparser"
    - "0.1_density"
    - "0.2_density"
petersen_n_k:
  - n: 5
    k: 2
  - n: 7
    k: 2
  - n: 10
    k: 2
cordones:
  - n: 5
  - n: 6
  - n: 7
  - n: 8

# Maxcut
maxcut:
  max_vertices: 5000
  min_vertices: 5000
  weighted: False
  projector: 
    # - "sparser"
    # - "sparse"
    # - "0.1_density"
    # - "0.2_density"
    # - "0.05_density"
    - "0.01_density"

  projection:
    - 0.1
    - 0.2
    # - 0.5
  results:
    min_vertices: 5000
    max_vertices: 5000


# Maxsat
maxsat:
  variables:
    # - 1000
    # - 1500
    # - 2000
    - 5000
  C:
    # - 0.1
    - 0.5
    - 1
    - 2
    # - 10
    # - 20
  projector:
    - "sparse"
    # - "sparser"
    # - "0.1_density"
    - "0.2_density"
  projection:
    - 0.1
    - 0.2
    # - 0.5
